### PR TITLE
Changes made in CSS to add adjust the text

### PR DESCRIPTION
**Pull request by Mahesh-Mavuri**
#30 Made changes in the index.html and in CSS to adjust till 400px width and tested in Chrome. Please recert back if there are any issues.

### CODE REVIEW

**Comment by anktrj** [comment]
Screenshot from 2019-10-05 18-43-03
You are good to go. Little tweaks required. I suggest you to make both the tittles at center.
Feel free to ask.

**Comment by Mahesh-Mavuri** [comment]
@ankiiitraj  Can I use Bootstrap for the code as I may need to change many things to get the things as expected?

**Comment by anktrj** [comment]
@Mahesh-Mavuri You can use bootstrap. Feel free to ask for any assistance

**Comment by Mahesh-Mavuri** [comment]
@ankiiitraj I am Changing the entire attendees/index.html. Don't assign mobile views to anyone else.

**Comment by anktrj** [comment]
I will be reviewing the changes tomorrow. Thanks @Mahesh-Mavuri

**Pull request closed without merging**
